# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/centralPanel.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CentralPanel(object):
    def setupUi(self, CentralPanel):
        CentralPanel.setObjectName(_fromUtf8("CentralPanel"))
        CentralPanel.resize(657, 764)
        self.gridLayout_4 = QtGui.QGridLayout(CentralPanel)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(CentralPanel)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.code_field_options = QtGui.QHBoxLayout(self.layoutWidget)
        self.code_field_options.setSpacing(0)
        self.code_field_options.setObjectName(_fromUtf8("code_field_options"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.field_path = QtGui.QLabel(self.layoutWidget)
        self.field_path.setAlignment(QtCore.Qt.AlignCenter)
        self.field_path.setObjectName(_fromUtf8("field_path"))
        self.horizontalLayout.addWidget(self.field_path)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_reloadScript = QtGui.QPushButton(self.layoutWidget)
        self.btn_reloadScript.setObjectName(_fromUtf8("btn_reloadScript"))
        self.horizontalLayout.addWidget(self.btn_reloadScript)
        self.btn_show = QtGui.QPushButton(self.layoutWidget)
        self.btn_show.setObjectName(_fromUtf8("btn_show"))
        self.horizontalLayout.addWidget(self.btn_show)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.numbers = NumberBar(self.layoutWidget)
        self.numbers.setObjectName(_fromUtf8("numbers"))
        self.horizontalLayout_3.addWidget(self.numbers)
        self.field_script = QtGui.QPlainTextEdit(self.layoutWidget)
        self.field_script.setDocumentTitle(_fromUtf8(""))
        self.field_script.setPlainText(_fromUtf8(""))
        self.field_script.setBackgroundVisible(False)
        self.field_script.setObjectName(_fromUtf8("field_script"))
        self.horizontalLayout_3.addWidget(self.field_script)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.code_field_options.addLayout(self.verticalLayout_4)
        self.optionsBar = QtGui.QVBoxLayout()
        self.optionsBar.setContentsMargins(15, -1, -1, -1)
        self.optionsBar.setObjectName(_fromUtf8("optionsBar"))
        self.gruopSize = QtGui.QGroupBox(self.layoutWidget)
        self.gruopSize.setObjectName(_fromUtf8("gruopSize"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gruopSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.gruopSize)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.figHeight = QtGui.QDoubleSpinBox(self.gruopSize)
        self.figHeight.setDecimals(1)
        self.figHeight.setMaximum(260.0)
        self.figHeight.setSingleStep(0.5)
        self.figHeight.setObjectName(_fromUtf8("figHeight"))
        self.gridLayout_2.addWidget(self.figHeight, 1, 3, 1, 1)
        self.radioSizeCombo = QtGui.QRadioButton(self.gruopSize)
        self.radioSizeCombo.setChecked(True)
        self.radioSizeCombo.setObjectName(_fromUtf8("radioSizeCombo"))
        self.gridLayout_2.addWidget(self.radioSizeCombo, 0, 0, 1, 1)
        self.combosize = QtGui.QComboBox(self.gruopSize)
        self.combosize.setObjectName(_fromUtf8("combosize"))
        self.gridLayout_2.addWidget(self.combosize, 0, 1, 1, 1)
        self.figWidth = QtGui.QDoubleSpinBox(self.gruopSize)
        self.figWidth.setDecimals(1)
        self.figWidth.setMaximum(200.0)
        self.figWidth.setSingleStep(0.5)
        self.figWidth.setObjectName(_fromUtf8("figWidth"))
        self.gridLayout_2.addWidget(self.figWidth, 1, 1, 1, 1)
        self.radiocustom = QtGui.QRadioButton(self.gruopSize)
        self.radiocustom.setObjectName(_fromUtf8("radiocustom"))
        self.gridLayout_2.addWidget(self.radiocustom, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        self.optionsBar.addWidget(self.gruopSize)
        self.GroupoutputFile = QtGui.QGroupBox(self.layoutWidget)
        self.GroupoutputFile.setObjectName(_fromUtf8("GroupoutputFile"))
        self.gridLayout = QtGui.QGridLayout(self.GroupoutputFile)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.GroupoutputFile)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.GroupoutputFile)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.fieldFIG = QtGui.QLineEdit(self.GroupoutputFile)
        self.fieldFIG.setObjectName(_fromUtf8("fieldFIG"))
        self.gridLayout.addWidget(self.fieldFIG, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.GroupoutputFile)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.GroupoutputFile)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.btn_fig = QtGui.QPushButton(self.GroupoutputFile)
        self.btn_fig.setObjectName(_fromUtf8("btn_fig"))
        self.gridLayout.addWidget(self.btn_fig, 1, 3, 1, 1)
        self.btn_Eps = QtGui.QPushButton(self.GroupoutputFile)
        self.btn_Eps.setObjectName(_fromUtf8("btn_Eps"))
        self.gridLayout.addWidget(self.btn_Eps, 0, 3, 1, 1)
        self.fieldEPS = QtGui.QLineEdit(self.GroupoutputFile)
        self.fieldEPS.setObjectName(_fromUtf8("fieldEPS"))
        self.gridLayout.addWidget(self.fieldEPS, 0, 2, 1, 1)
        self.latexLabel = QtGui.QCheckBox(self.GroupoutputFile)
        self.latexLabel.setObjectName(_fromUtf8("latexLabel"))
        self.gridLayout.addWidget(self.latexLabel, 2, 2, 1, 1)
        self.checkAutoshow = QtGui.QCheckBox(self.GroupoutputFile)
        self.checkAutoshow.setObjectName(_fromUtf8("checkAutoshow"))
        self.gridLayout.addWidget(self.checkAutoshow, 2, 3, 1, 1)
        self.optionsBar.addWidget(self.GroupoutputFile)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.repl_field = QtGui.QPlainTextEdit(self.groupBox_4)
        self.repl_field.setObjectName(_fromUtf8("repl_field"))
        self.verticalLayout.addWidget(self.repl_field)
        self.optionsBar.addWidget(self.groupBox_4)
        self.code_field_options.addLayout(self.optionsBar)
        self.code_field_options.setStretch(0, 1)
        self.gridLayout_4.addWidget(self.splitter, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(CentralPanel)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboStyles = QtGui.QComboBox(self.groupBox_3)
        self.comboStyles.setObjectName(_fromUtf8("comboStyles"))
        self.horizontalLayout_2.addWidget(self.comboStyles)
        self.btn_reloadStyle = QtGui.QPushButton(self.groupBox_3)
        self.btn_reloadStyle.setObjectName(_fromUtf8("btn_reloadStyle"))
        self.horizontalLayout_2.addWidget(self.btn_reloadStyle)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.insertElement = QtGui.QGroupBox(CentralPanel)
        self.insertElement.setObjectName(_fromUtf8("insertElement"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.insertElement)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cmb_Element = QtGui.QComboBox(self.insertElement)
        self.cmb_Element.setObjectName(_fromUtf8("cmb_Element"))
        self.horizontalLayout_10.addWidget(self.cmb_Element)
        self.horizontalLayout_4.addWidget(self.insertElement)
        self.insertType = QtGui.QGroupBox(CentralPanel)
        self.insertType.setObjectName(_fromUtf8("insertType"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.insertType)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cmb_type = QtGui.QComboBox(self.insertType)
        self.cmb_type.setObjectName(_fromUtf8("cmb_type"))
        self.horizontalLayout_12.addWidget(self.cmb_type)
        self.btn_insert = QtGui.QPushButton(self.insertType)
        self.btn_insert.setObjectName(_fromUtf8("btn_insert"))
        self.horizontalLayout_12.addWidget(self.btn_insert)
        self.horizontalLayout_4.addWidget(self.insertType)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(CentralPanel)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.codeGen = QtGui.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codeGen.sizePolicy().hasHeightForWidth())
        self.codeGen.setSizePolicy(sizePolicy)
        self.codeGen.setMaximumSize(QtCore.QSize(16777215, 50))
        self.codeGen.setObjectName(_fromUtf8("codeGen"))
        self.horizontalLayout_5.addWidget(self.codeGen)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(CentralPanel)
        QtCore.QMetaObject.connectSlotsByName(CentralPanel)
        CentralPanel.setTabOrder(self.comboStyles, self.btn_reloadStyle)
        CentralPanel.setTabOrder(self.btn_reloadStyle, self.cmb_Element)
        CentralPanel.setTabOrder(self.cmb_Element, self.cmb_type)
        CentralPanel.setTabOrder(self.cmb_type, self.btn_insert)
        CentralPanel.setTabOrder(self.btn_insert, self.codeGen)
        CentralPanel.setTabOrder(self.codeGen, self.radioSizeCombo)
        CentralPanel.setTabOrder(self.radioSizeCombo, self.combosize)
        CentralPanel.setTabOrder(self.combosize, self.radiocustom)
        CentralPanel.setTabOrder(self.radiocustom, self.figWidth)
        CentralPanel.setTabOrder(self.figWidth, self.figHeight)
        CentralPanel.setTabOrder(self.figHeight, self.fieldEPS)
        CentralPanel.setTabOrder(self.fieldEPS, self.btn_Eps)
        CentralPanel.setTabOrder(self.btn_Eps, self.fieldFIG)
        CentralPanel.setTabOrder(self.fieldFIG, self.btn_fig)
        CentralPanel.setTabOrder(self.btn_fig, self.latexLabel)
        CentralPanel.setTabOrder(self.latexLabel, self.repl_field)

    def retranslateUi(self, CentralPanel):
        CentralPanel.setWindowTitle(_translate("CentralPanel", "GUISSE", None))
        self.field_path.setText(_translate("CentralPanel", "File name", None))
        self.btn_reloadScript.setText(_translate("CentralPanel", "Reload", None))
        self.btn_show.setText(_translate("CentralPanel", "Show", None))
        self.gruopSize.setTitle(_translate("CentralPanel", "Output Size: WxH", None))
        self.label.setText(_translate("CentralPanel", "H:", None))
        self.radioSizeCombo.setText(_translate("CentralPanel", "WxH", None))
        self.radiocustom.setText(_translate("CentralPanel", "W:", None))
        self.GroupoutputFile.setTitle(_translate("CentralPanel", "Output Files", None))
        self.label_7.setText(_translate("CentralPanel", "FIG", None))
        self.label_8.setText(_translate("CentralPanel", ":", None))
        self.label_5.setText(_translate("CentralPanel", "EPS", None))
        self.label_6.setText(_translate("CentralPanel", ":", None))
        self.btn_fig.setText(_translate("CentralPanel", "Export FIG", None))
        self.btn_Eps.setText(_translate("CentralPanel", "Export EPS", None))
        self.latexLabel.setText(_translate("CentralPanel", "Fig Latex Friendly", None))
        self.checkAutoshow.setText(_translate("CentralPanel", "Auto Show", None))
        self.groupBox_4.setTitle(_translate("CentralPanel", "Replacements", None))
        self.groupBox_3.setTitle(_translate("CentralPanel", "Template", None))
        self.btn_reloadStyle.setText(_translate("CentralPanel", "Reload", None))
        self.insertElement.setTitle(_translate("CentralPanel", "Element", None))
        self.insertType.setTitle(_translate("CentralPanel", "Type", None))
        self.btn_insert.setText(_translate("CentralPanel", "Insert at the end", None))
        self.groupBox_2.setTitle(_translate("CentralPanel", "Code", None))

from Small_Editor import NumberBar
